### ISSUE TITLE
Hinzufügen von Links in Steckbriefen

### ISSUE THREAD

**Issue by widominik** [kjoscha/innoMap#10]
Oft haben Projekte noch Möglichkeiten, über angefügte URLs mehr Informationen zu liefern. Wäre es möglich, vielleicht ähnlich wie im CMS, so etwas hinzuzufügen? Für Smartboardeinsätze wäre es gut, wenn solche Links immer in einem verkleinerten Fenster (Popup) aufgehen, sodass man es wieder danach wieder schließen kann und wieder auf der Karte ist. Das wurde bisher über Javascript gehandhabt, weil standardmäßig neue Fenster ja aufgrund von Browsereinstellungen in einem neuen Tab geöffnet werden - im Vollbildmodus vielleicht nicht so geeignet.
![unbenannt](https://cloud.githubusercontent.com/assets/22976137/19771180/4c51963a-9c62-11e6-843d-d3e689bdf657.png)

**Comment by kjoscha** [comment]
done
