### ISSUE TITLE
Subregionen werden immer in die erste Karte eingefügt

### ISSUE THREAD

**Issue by widominik** [kjoscha/innoMap#21]
Ich habe eine zweite Hauptregion angelegt und wollte dort analog zur 
Main Scene (Hauptregion) -> EUREF-Karte (Subregion)
Hauptkarte (Hauptregion) -> Großstadt (Subregion)
anlegen. 
Nach dem Speichern befindet sich die Großstadt jedoch nicht in der neuen Hauptregion sondern in der alten.

**Comment by kjoscha** [comment]
ok, danke. Kümmere mich gleich drum
