### ISSUE TITLE
Beschriftungen der Filter gehen außerhalb der Box auf

### ISSUE THREAD

**Issue by widominik** [kjoscha/innoMap#4]
Die Layer mit den Namen der Navigationsfilter auf der linken Seite gehen bereits auf, wenn man über den Platz seine Maus hält, wohin die jeweiligen Nametags reichen. In der gelben Markierung kann man so nur sehr stark eingeschränkt die Karte verschieben.

![navibug](https://cloud.githubusercontent.com/assets/22976137/19602413/72bc9810-97ad-11e6-8e5f-9d6f1ccf0b54.png)

**Comment by magdalena19** [comment]
okay. sehr hilfreich so mit dem Screenshot übrigens :+1:

**Comment by magdalena19** [comment]
Übrigens ist alles was Design angeht erstmal total vorläufig - habe Anna schon bescheid gegeben, dass wir demnächst mal auf sie zukommen diesbezüglich...

**Comment by kjoscha** [comment]
fixed
