### ISSUE TITLE
Bearbeitung eines Projektpins: Kategorie wird zurückgesetzt

### ISSUE THREAD

**Issue by widominik** [kjoscha/innoMap#7]
Bei der Bearbeitung von Projektpins wird die Auswahl des Navigationslayers standardmäßig immer wieder auf die erste Kategorie gesetzt anstatt es bei der Kategorie bleibt, welche vormals ausgewählt wurde.
![unbenannt](https://cloud.githubusercontent.com/assets/22976137/19767855/16e12d60-9c55-11e6-8fcc-a2858e5c8d32.png)

**Comment by kjoscha** [comment]
glaube es ist gefixed. @widominik Bitte nochmal testen
