### ISSUE TITLE
Projektpins "verschwinden" etwas in der Karte

### ISSUE THREAD

**Issue by widominik** [kjoscha/innoMap#9]
Gerade nachdem wir nun farbige Wimmelbilder haben, gehen Projektpins in den Farben etwas verloren und könnten schwieriger gesehen werden. In der alten Karte gibt es mit opacity einen gewissen weißen Schleier, der die Grafiken etwas verblassen lässt und dadurch die Pins stärker hervorhebt. Das hätten wir gerne in einer ähnlichen Art wieder.
![unbenannt](https://cloud.githubusercontent.com/assets/22976137/19770923/62d17732-9c61-11e6-918c-17a443a9834d.png)

**Comment by kjoscha** [comment]
done
